places = JSON.parse(localStorage.getItem("places"));
if (!places) {
  localStorage.setItem("places",JSON.stringify([
      {
        area: "Nungambakam",
        category_name: "Parks & Rooms",
        description:
          "Airborne - The Trampoline Park In Nungambakkam is bae for a number of reasons. Not only does it present a fresh break from your monotonous cafe and movie outings with friends.",
        detail_page: "",
        image_link: "../../assets/images/trampoline.jpg",
        place_name: "Airborne Trampoline park",
        unique_id: "c9ea4ed9-eb10-4c45-b0e5-01603365bcdf",
      },

      {
        Descptn:
          "This mall was jointly developed by Phoenix Mills Limited and Crest Ventures Ltd. Phoenix Mall Chennai is part of a development which includes a premium residential space as part of Phase I. Phase II development includes a luxury mall called Palladium and residential space. Phoenix Mall features an 11-screen multiplex which is also Chennai's first IMAX screen. Address:183, Great Southern Trunk Rd, Arcot Rd, Vadapalani, Chennai, Tamil Nadu 600026",
        Information: "",
        area: "select",
        banner: "/assets/images/phoneix.jpg",
        branch1Img: "/assets/images/MC donald's forum mall.jpg",
        branch1Name: "MC donald's",
        branch1time: "11am - 11.59pm",
        branch2Img: "/assets/images/pizza hut marina mall.jpg",
        branch2Name: "Pizza hut",
        branch2time: "11am - 11.59pm",
        branch3Img: "/assets/images/taco-bell.png",
        branch3Name: "Taco Bell",
        branch3time: "11am - 11.59pm",
        branch4Img: "/assets/images/belgian waffle marina mall.webp",
        branch4Name: "Belgian wafffle",
        branch4time: "11am - 11.59pm",
        branch5Img: "/assets/images/pandikadai forum mall.jpg",
        branch5Name: "Pandikadai",
        branch5time: "11am - 11.59pm",
        category_name: "Malls",
        description:
          "Phoenix Mall Chennai is part of a development which includes a premium residential space as part of Phase I",
        detail_page: "",
        image_link: "/assets/images/phoneix.jpg",
        place_name: "Phoenix mall",
        store1Abt: "Electronics",
        store1Img: "/assets/images/croma.png",
        store1Name: "croma",
        store2Abt: "Bags & Luggage | Foot fashion",
        store2Img: "/assets/images/bata.png",
        store2Name: "Bata",
        store3Abt: "Departmental store",
        store3Img: "/assets/images/Lifestyle.jpg",
        store3Name: "Lifestyle",
        store4Abt: "Lens fashion",
        store4Img: "/assets/images/lenskart.png",
        store4Name: "Lenskart",
        store5Abt: "Men's Fashion | Women's Fashion",
        store5Img: "/assets/images/van heusen.jpg",
        store5Name: "Van Heusen",
        store6Abt: "General Fashion",
        store6Img: "/assets/images/allen solly.png",
        store6Name: "Allen Solly",
        store7Abt: "Beauty salon | Health & Beauty",
        store7Img: "/assets/images/Mamaearth.jpeg",
        store7Name: "Mamaearth",
        store8Abt: "Sports & Fitness",
        store8Img: "/assets/images/Nike.png",
        store8Name: "Nike",
        unique_id: "9724f3a2-7c32-4671-a7e6-e7d9edb89026",
      },
      {
        Descptn: "",
        Information: "",
        area: "select",
        banner: "/assets/images/vijya mall banner.png",
        branch1Img: "/assets/images/MC donald's forum mall.jpg",
        branch1Name: "MC donald's",
        branch1time: "11am - 11.59pm",
        branch2Img: "/assets/images/pizza hut marina mall.jpg",
        branch2Name: "Pizza hut",
        branch2time: "11am - 11.59pm",
        branch3Img: "/assets/images/taco-bell.png",
        branch3Name: "Taco Bell",
        branch3time: "11am - 11.59pm",
        branch4Img: "/assets/images/belgian waffle marina mall.webp",
        branch4Name: "Belgian wafffle",
        branch4time: "11am - 11.59pm",
        branch5Img: "/assets/images/pandikadai forum mall.jpg",
        branch5Name: "Pandikadai",
        branch5time: "11am - 11.59pm",
        category_name: "Malls",
        description:
          "Entertainment is Chennai's 1st and largest Board Gaming venture.",
        detail_page: "",
        image_link: "/assets/images/vijya mall banner.png",
        place_name: "Nexus Vijaya Mall",
        store1Abt: "Men's Fashion | Women's Fashion | Health & Beauty",
        store1Img: "/assets/images/Nykaa.jpg",
        store1Name: "Nykaa",
        store2Abt: "Bags & Luggage | Foot fashion",
        store2Img: "/assets/images/bata.png",
        store2Name: "Bata",
        store3Abt: "Entertainment",
        store3Img: "/assets/images/funcity.jpg",
        store3Name: "Funcity",
        store4Abt: "Fashion shoes",
        store4Img: "/assets/images/Adidas.webp",
        store4Name: "Adidas",
        store5Abt: "Fashion",
        store5Img: "/assets/images/trends-woman.png",
        store5Name: "Trends Woman",
        store6Abt: "Departmental store",
        store6Img: "/assets/images/Lifestyle.jpg",
        store6Name: "Lifestyle",
        store7Abt: "Hair Dressing",
        store7Img: "/assets/images/Tony and guy.png",
        store7Name: "Tony&Guy",
        store8Abt: "Lens Fashion",
        store8Img: "/assets/images/lenskart.png",
        store8Name: "Lenskart",
        unique_id: "9724f3a2-7c32-4671-a7e6-e7d9edb89026",
      },
      {
        area: "select",
        category_name: "Beach",
        description:
          "Marina beach in Chennai along the Bay of Bengal is India's longest and world's second longest beach.",
        detail_page: "",
        image_link: "/assets/images/Marina-Beach.jpg",
        place_name: "Marina beach",
        unique_id: "e1946b64-e4df-4ddc-a970-4d92a5e54806",
      },
      {
        area: "Anna-nagar",
        category_name: "select",
        description:
          "It is the 8th smallest National park of India and the main attraction of the park is the 20 million years of old Tyrannosaurus",
        detail_page: "",
        image_link: "/assets/images/guindy.jpg",
        place_name: "Guindy National Park",
        unique_id: "6293c538-a28c-41ef-91cb-d969a9d2d3ac",
      },
      {
        area: "select",
        category_name: "Beach",
        description:
          " The Kovalam beach is popular for its splendid view of the sunset.",
        detail_page: "",
        image_link: "../../assets/images/Kovalam-Beach.webp",
        place_name: "Kovalam beach",
        unique_id: "6293c538-a28c-41ef-91cb-d969a9d2d3ab",
      },
      {
        area: "Anna-nagar",
        category_name: "select",
        description:
          "B. M. Birla Planetarium is a large planetarium in Chennai providing a virtual tour of the night sky and holding cosmic shows on a specially perforated hemispherical aluminium inner dome.",
        detail_page: "",
        image_link: "../../assets/images/planatorium.jpg",
        place_name: "Brilla Planatorium",
        unique_id: "6293c538-a28c-41ef-91cb-d969a9d2d2cd",
      },
    ])
  );
}
